Repository HELLO2O/ReactStudy, pull requests merged in 2025-04, with the labels that each got.

#1 config 변경 및 main과의 충돌 해결
  jsconfig.json
  vite.config.js
Labels: documentation

#2 chore(config): 절대 경로(@) 설정 및 vite.config 정리
  eslint.config.js
  jsconfig.json
  src/App.jsx
  src/components/Button.jsx
  src/components/Navbar.jsx
  src/components/ProductItem.jsx
  src/components/ProductList.jsx
  src/components/Title.jsx
  src/main.jsx
  src/pages/ProductPage/index.jsx
  vite.config.js
Labels: chore

#3 feat(order): 주문 상태/ 결제/ 배송 카드 만들기
  jsconfig.json
  src/App.jsx
  src/components/Card.jsx
  src/components/ProductList.jsx
  src/main.jsx
  src/pages/OrderPage/OrderDeliveryCard.jsx
  src/pages/OrderPage/OrderPaymentCard.jsx
  src/pages/OrderPage/OrderStatusCard.jsx
  src/pages/OrderPage/index.jsx
  src/pages/ProductPage/ProductPage.jsx
Labels: feature

#4 feat(order): 주문 상태/결제/배송 카드 컴포넌트 추가
  jsconfig.json
  package-lock.json
  package.json
  src/App.jsx
  src/api/apiClient.js
  src/api/productsAPI.js
  src/components/Card.jsx
  src/components/Title.jsx
  src/hooks/useProducts.js
  src/main.jsx
  src/pages/OrderPage/OrderDeliveryCard.jsx
  src/pages/OrderPage/OrderPaymentCard.jsx
  src/pages/OrderPage/OrderStatusCard.jsx
  src/pages/OrderPage/index.jsx
Labels: feature
